---
abstract: 'Database Schema for Interchange 6'
author:
  - 'Stefan Hornburg (Racke) <racke@linuxia.de>'
build_requires:
  DBICx::TestDatabase: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Interchange6-Schema
no_index:
  directory:
    - t
    - inc
requires:
  DBIx::Class: 0
  DBIx::Class::EncodedColumn: 0
  DBIx::Class::TimeStamp: 0
  SQL::Translator: 0.11016
resources:
  bugtracker: https://github.com/interchange/interchange6-schema/issues
  repository: https://github.com/interchange/interchange6-schema.git
version: 0.004
